<html>
<head>
	<title>Zend-Login</title>
	<link rel='stylesheet' href='<?php echo $this->baseUrl;?>/css/login.css' >
	<script type="text/javascript" src='<?php echo $this->baseUrl;?>/js/jquery/jquery-1.7.2.min.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl;?>/js/login.js'></script>
	<script type='text/javascript'> 
	    var url = '<?php echo $this->baseUrl; ?>'; 
	</script>
</head>
<div id='formAjax'>	
	<form class='login'>
		<div style='float:right;'><label>Login </label></div><br><br>
		<div><label>Usuario: </label>
			<input type='text' class='usuario' id='usuario' value=''>
		</div>
		<div><label>Clave:</label>	
			<input type='password' class='clave' id='clave' value=''>
		</div>
		<div id='msjLogin'><label>Llenar ambos campos.</label></div>
		<div style='float:right;'><input type='submit' id='btnLogin' value='Enviar'></div>
	</form>
</div>
</body>
</html>
